CREATE TABLE customers 
(
    CustomerID	VARCHAR(512),
    CompanyName	VARCHAR(512),
    ContactName	VARCHAR(512),
    ContactTitle	VARCHAR(512),
    City	VARCHAR(512),
    Region	VARCHAR(512),
    PostalCode	VARCHAR(512),
    Country	VARCHAR(512)
);

INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('ALFKI', 'Alfreds Futterkiste', 'Maria Anders', 'Sales Representative', 'Berlin', '', '12209', 'Germany');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('ANATR', 'Ana Trujillo Emparedados y helados', 'Ana Trujillo', 'Owner', 'M�xico D.F.', '', '05021', 'Mexico');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('ANTON', 'Antonio Moreno Taquer�a', 'Antonio Moreno', 'Owner', 'M�xico D.F.', '', '05023', 'Mexico');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('AROUT', 'Around the Horn', 'Thomas Hardy', 'Sales Representative', 'London', '', 'WA1 1DP', 'UK');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('BERGS', 'Berglunds snabbkop', 'Christina Berglund', 'Order Administrator', 'Lule�', '', 'S-958 22', 'Sweden');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('BLAUS', 'Blauer See Delikatessen', 'Hanna Moos', 'Sales Representative', 'Mannheim', '', '68306', 'Germany');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('BLONP', 'Blondesddsl pere et fils', 'Fr�d�rique Citeaux', 'Marketing Manager', 'Strasbourg', '', '67000', 'France');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('BOLID', 'Bolido Comidas preparadas', 'Mart�n Sommer', 'Owner', 'Madrid', '', '28023', 'Spain');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('BONAP', 'Bon app', 'Laurence Lebihan', 'Owner', 'Marseille', '', '13008', 'France');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('BOTTM', 'Bottom-Dollar Markets', 'Elizabeth Lincoln', 'Accounting Manager', 'Tsawassen', 'BC', 'T2F 8M4', 'Canada');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('BSBEV', "B's Beverages", 'Victoria Ashworth', 'Sales Representative', 'London', '', 'EC2 5NT', 'UK');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('CACTU', 'Cactus Comidas para llevar', 'Patricio Simpson', 'Sales Agent', 'Buenos Aires', '', '1010', 'Argentina');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('CENTC', 'Centro comercial Moctezuma', 'Francisco Chang', 'Marketing Manager', 'M�xico D.F.', '', '05022', 'Mexico');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('CHOPS', 'Chop-suey Chinese', 'Yang Wang', 'Owner', 'Bern', '', '3012', 'Switzerland');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('COMMI', 'Comercio Mineiro', 'Pedro Afonso', 'Sales Associate', 'Sao Paulo', 'SP', '05432-043', 'Brazil');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('CONSH', 'Consolidated Holdings', 'Elizabeth Brown', 'Sales Representative', 'London', '', 'WX1 6LT', 'UK');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('DRACD', 'Drachenblut Delikatessen', 'Sven Ottlieb', 'Order Administrator', 'Aachen', '', '52066', 'Germany');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('DUMON', 'Du monde entier', 'Janine Labrune', 'Owner', 'Nantes', '', '44000', 'France');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('EASTC', 'Eastern Connection', 'Ann Devon', 'Sales Agent', 'London', '', 'WX3 6FW', 'UK');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('ERNSH', 'Ernst Handel', 'Roland Mendel', 'Sales Manager', 'Graz', '', '8010', 'Austria');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('FAMIA', 'Familia Arquibaldo', 'Aria Cruz', 'Marketing Assistant', 'Sao Paulo', 'SP', '05442-030', 'Brazil');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('FISSA', 'FISSA Fabrica Inter. Salchichas S.A.', 'Diego Roel', 'Accounting Manager', 'Madrid', '', '28034', 'Spain');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('FOLIG', 'Folies gourmandes', 'Martine Ranc�', 'Assistant Sales Agent', 'Lille', '', '59000', 'France');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('FOLKO', 'Folk och fa HB', 'Maria Larsson', 'Owner', 'Br�cke', '', 'S-844 67', 'Sweden');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('FRANK', 'Frankenversand', 'Peter Franken', 'Marketing Manager', 'M�nchen', '', '80805', 'Germany');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('FRANR', 'France restauration', 'Carine Schmitt', 'Marketing Manager', 'Nantes', '', '44000', 'France');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('FRANS', 'Franchi S.p.A.', 'Paolo Accorti', 'Sales Representative', 'Torino', '', '10100', 'Italy');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('FURIB', 'Furia Bacalhau e Frutos do Mar', 'Lino Rodriguez', 'Sales Manager', 'Lisboa', '', '1675', 'Portugal');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('GALED', 'Galer�a del gastronomo', 'Eduardo Saavedra', 'Marketing Manager', 'Barcelona', '', '08022', 'Spain');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('GODOS', 'Godos Cocina Tipica', 'Jos� Pedro Freyre', 'Sales Manager', 'Sevilla', '', '41101', 'Spain');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('GOURL', 'Gourmet Lanchonetes', 'Andr� Fonseca', 'Sales Associate', 'Campinas', 'SP', '04876-786', 'Brazil');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('GREAL', 'Great Lakes Food Market', 'Howard Snyder', 'Marketing Manager', 'Eugene', 'OR', '97403', 'USA');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('GROSR', 'GROSELLA-Restaurante', 'Manuel Pereira', 'Owner', 'Caracas', 'DF', '1081', 'Venezuela');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('HANAR', 'Hanari Carnes', 'Mario Pontes', 'Accounting Manager', 'Rio de Janeiro', 'RJ', '05454-876', 'Brazil');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('HILAA', 'HILARION-Abastos', 'Carlos Hern�ndez', 'Sales Representative', 'San Crist�bal', 'T�chira', '5022', 'Venezuela');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('HUNGC', 'Hungry Coyote Import Store', 'Yoshi Latimer', 'Sales Representative', 'Elgin', 'OR', '97827', 'USA');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('HUNGO', 'Hungry Owl All-Night Grocers', 'Patricia McKenna', 'Sales Associate', 'Cork', 'Co. Cork', '', 'Ireland');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('ISLAT', 'Island Trading', 'Helen Bennett', 'Marketing Manager', 'Cowes', 'Isle of Wight', 'PO31 7PJ', 'UK');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('KOENE', 'Koniglich Essen', 'Philip Cramer', 'Sales Associate', 'Brandenburg', '', '14776', 'Germany');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('LACOR', 'La corne dabondance', 'Daniel Tonini', 'Sales Representative', 'Versailles', '', '78000', 'France');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('LAMAI', "La maison d'Asie", 'Annette Roulet', 'Sales Manager', 'Toulouse', '', '31000', 'France');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('LAUGB', 'Laughing Bacchus Wine Cellars', 'Yoshi Tannamuri', 'Marketing Assistant', 'Vancouver', 'BC', 'V3F 2K1', 'Canada');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('LAZYK', 'Lazy K Kountry Store', 'John Steel', 'Marketing Manager', 'Walla Walla', 'WA', '99362', 'USA');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('LEHMS', 'Lehmanns Marktstand', 'Renate Messner', 'Sales Representative', 'Frankfurt a.M.', '', '60528', 'Germany');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('LETSS', "Let's Stop N Shop", 'Jaime Yorres', 'Owner', 'San Francisco', 'CA', '94117', 'USA');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('LILAS', 'LILA-Supermercado', 'Carlos Gonz�lez', 'Accounting Manager', 'Barquisimeto', 'Lara', '3508', 'Venezuela');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('LINOD', 'LINO-Delicateses', 'Felipe Izquierdo', 'Owner', 'I. de Margarita', 'Nueva Esparta', '4980', 'Venezuela');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('LONEP', 'Lonesome Pine Restaurant', 'Fran Wilson', 'Sales Manager', 'Portland', 'OR', '97219', 'USA');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('MAGAA', 'Magazzini Alimentari Riuniti', 'Giovanni Rovelli', 'Marketing Manager', 'Bergamo', '', '24100', 'Italy');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('MAISD', 'Maison Dewey', 'Catherine Dewey', 'Sales Agent', 'Bruxelles', '', 'B-1180', 'Belgium');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('MEREP', 'Mere Paillarde', 'Jean Fresni�re', 'Marketing Assistant', 'Montr�al', 'Qu�bec', 'H1J 1C3', 'Canada');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('MORGK', 'Morgenstern Gesundkost', 'Alexander Feuer', 'Marketing Assistant', 'Leipzig', '', '04179', 'Germany');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('NORTS', 'North/South', 'Simon Crowther', 'Sales Associate', 'London', '', 'SW7 1RZ', 'UK');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('OCEAN', 'Oceano Atlantico Ltda.', 'Yvonne Moncada', 'Sales Agent', 'Buenos Aires', '', '1010', 'Argentina');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('OLDWO', 'Old World Delicatessen', 'Rene Phillips', 'Sales Representative', 'Anchorage', 'AK', '99508', 'USA');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('OTTIK', 'Ottilies Kaseladen', 'Henriette Pfalzheim', 'Owner', 'K�ln', '', '50739', 'Germany');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('PARIS', 'Paris specialites', 'Marie Bertrand', 'Owner', 'Paris', '', '75012', 'France');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('PERIC', 'Pericles Comidas clasicas', 'Guillermo Fern�ndez', 'Sales Representative', 'M�xico D.F.', '', '05033', 'Mexico');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('PICCO', 'Piccolo und mehr', 'Georg Pipps', 'Sales Manager', 'Salzburg', '', '5020', 'Austria');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('PRINI', 'Princesa Isabel Vinhos', 'Isabel de Castro', 'Sales Representative', 'Lisboa', '', '1756', 'Portugal');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('QUEDE', 'Que Delicia', 'Bernardo Batista', 'Accounting Manager', 'Rio de Janeiro', 'RJ', '02389-673', 'Brazil');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('QUEEN', 'Queen Cozinha', 'L�cia Carvalho', 'Marketing Assistant', 'Sao Paulo', 'SP', '05487-020', 'Brazil');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('QUICK', 'QUICK-Stop', 'Horst Kloss', 'Accounting Manager', 'Cunewalde', '', '01307', 'Germany');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('RANCH', 'Rancho grande', 'Sergio Guti�rrez', 'Sales Representative', 'Buenos Aires', '', '1010', 'Argentina');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('RATTC', 'Rattlesnake Canyon Grocery', 'Paula Wilson', 'Assistant Sales Representative', 'Albuquerque', 'NM', '87110', 'USA');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('REGGC', 'Reggiani Caseifici', 'Maurizio Moroni', 'Sales Associate', 'Reggio Emilia', '', '42100', 'Italy');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('RICAR', 'Ricardo Adocicados', 'Janete Limeira', 'Assistant Sales Agent', 'Rio de Janeiro', 'RJ', '02389-890', 'Brazil');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('RICSU', 'Richter Supermarkt', 'Michael Holz', 'Sales Manager', 'Gen�ve', '', '1203', 'Switzerland');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('ROMEY', 'Romero y tomillo', 'Alejandra Camino', 'Accounting Manager', 'Madrid', '', '28001', 'Spain');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('SANTG', 'Sante Gourmet', 'Jonas Bergulfsen', 'Owner', 'Stavern', '', '4110', 'Norway');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('SAVEA', 'Save-a-lot Markets', 'Jose Pavarotti', 'Sales Representative', 'Boise', 'ID', '83720', 'USA');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('SEVES', 'Seven Seas Imports', 'Hari Kumar', 'Sales Manager', 'London', '', 'OX15 4NB', 'UK');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('SIMOB', 'Simons bistro', 'Jytte Petersen', 'Owner', 'Kobenhavn', '', '1734', 'Denmark');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('SPECD', 'Specialites du monde', 'Dominique Perrier', 'Marketing Manager', 'Paris', '', '75016', 'France');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('SPLIR', 'Split Rail Beer & Ale', 'Art Braunschweiger', 'Sales Manager', 'Lander', 'WY', '82520', 'USA');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('SUPRD', 'Supremes delices', 'Pascale Cartrain', 'Accounting Manager', 'Charleroi', '', 'B-6000', 'Belgium');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('THEBI', 'The Big Cheese', 'Liz Nixon', 'Marketing Manager', 'Portland', 'OR', '97201', 'USA');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('THECR', 'The Cracker Box', 'Liu Wong', 'Marketing Assistant', 'Butte', 'MT', '59801', 'USA');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('TOMSP', 'Toms Spezialitaten', 'Karin Josephs', 'Marketing Manager', 'M�nster', '', '44087', 'Germany');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('TORTU', 'Tortuga Restaurante', 'Miguel Angel Paolino', 'Owner', 'M�xico D.F.', '', '05033', 'Mexico');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('TRADH', 'Tradicao Hipermercados', 'Anabela Domingues', 'Sales Representative', 'Sao Paulo', 'SP', '05634-030', 'Brazil');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('TRAIH', "Trail's Head Gourmet Provisioners", 'Helvetius Nagy', 'Sales Associate', 'Kirkland', 'WA', '98034', 'USA');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('VAFFE', 'Vaffeljernet', 'Palle Ibsen', 'Sales Manager', '�rhus', '', '8200', 'Denmark');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('VICTE', 'Victuailles en stock', 'Mary Saveley', 'Sales Agent', 'Lyon', '', '69004', 'France');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('VINET', 'Vins et alcools Chevalier', 'Paul Henriot', 'Accounting Manager', 'Reims', '', '51100', 'France');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('WANDK', 'Die Wandernde Kuh', 'Rita M�ller', 'Sales Representative', 'Stuttgart', '', '70563', 'Germany');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('WARTH', 'Wartian Herkku', 'Pirkko Koskitalo', 'Accounting Manager', 'Oulu', '', '90110', 'Finland');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('WELLI', 'Wellington Importadora', 'Paula Parente', 'Sales Manager', 'Resende', 'SP', '08737-363', 'Brazil');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('WHITC', 'White Clover Markets', 'Karl Jablonski', 'Owner', 'Seattle', 'WA', '98128', 'USA');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('WILMK', 'Wilman Kala', 'Matti Karttunen', 'Owner/Marketing Assistant', 'Helsinki', '', '21240', 'Finland');
INSERT INTO customers (CustomerID, CompanyName, ContactName, ContactTitle, City, Region, PostalCode, Country) VALUES ('WOLZA', 'Wolski  Zajazd', 'Zbyszek Piestrzeniewicz', 'Owner', 'Warszawa', '', '01-012', 'Poland');
